version: '3.8'

services:
  redis:
    image: redis
    container_name: redis
    ports:
      - 6379:6379
    networks:
      - knowck_net


  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - /home/ubuntu/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - 9090:9090
    networks:
      - knowck_net


  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - 3000:3000
    networks:
      - knowck_net


  knowckknowck-backend:
    image: ${DOCKERHUB_USERNAME}/${DOCKER_IMAGE}
    container_name: ${DOCKER_IMAGE}
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8080:8080
    environment:
      PROFILE: prod
    depends_on:
      - redis
      - prometheus
      - grafana
    networks:
      - knowck_net



networks:
  knowck_net:
    driver: bridge
